### ISSUE TITLE
How  can I color my sketch drawing using Pen tool inside the shape boundaries?

### ISSUE THREAD

**Issue by mrpradipkumar46** [daihase/Sketch#8]
I want to colour the drawing  using  pen tool .And if the shape boundary is closed while colouring ..the colour should not come out from the boundary.. The feature is exactly like the fillcolour thru paint bucket.. Is it possible here?

**Comment by daihase** [comment]
@mrpradipkumar46 
In fact, that algorithm is difficult.
First of all, how do you decide the mask?
In order to clip,  boundary path of the mask is also required.
If complex graphics and stamps are nearby, the difficulty level is higher.

As a current implementation, incorporating them is somewhat difficult for me.
Sorry... 🙇

**Comment by mrpradipkumar46** [comment]
@daihase  I am using FloodFill Algorithm and working on customising it.. lets see if I could able to get the desired output.. Anyway thanks for cooperating.. am closing it ..
